#include <cstring>
#include <string>

#include <catch2/catch_test_macros.hpp>

#include "Connection.hpp"
#include "ReadOnlyDbFixture.hpp"
#include "compatibility.hpp"
#include "get_diag_rec.hpp"

// =============================================================================
// Tests for SQLDescribeCol based on ODBC specification:
// https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function
// =============================================================================

// =============================================================================
// Column Name
// =============================================================================

TEST_CASE("SQLDescribeCol returns correct column name.", "[query]") {
  // Doc: "SQLDescribeCol returns the result descriptor - column name, type,
  //       column size, decimal digits, and nullability - for one column in the
  //       result set."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#summary

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS MY_COLUMN");

  // When SQLDescribeCol is called for column 1
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the column name should be MY_COLUMN
  CHECK(std::string((char*)col_name) == "MY_COLUMN");
  CHECK(name_length == 9);
}

TEST_CASE("SQLDescribeCol returns empty string for expression column.", "[query]") {
  // Doc: "SQLDescribeCol retrieves the column name, type, and length generated by
  //       a SELECT statement. If the column is an expression, *ColumnName is either
  //       an empty string or a driver-defined name."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#comments

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 1 + 1");

  // When SQLDescribeCol is called for the expression column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the column name should be empty or driver-defined (Snowflake returns a name)
  CHECK(ret == SQL_SUCCESS);
}

// =============================================================================
// Column Name Truncation
// =============================================================================

TEST_CASE("SQLDescribeCol returns 01004 when column name is truncated.", "[query]") {
  // Doc: "01004 - String data, right truncated: The buffer *ColumnName was not
  //       large enough to return the entire column name, so the column name was
  //       truncated. The length of the untruncated column name is returned in
  //       *NameLengthPtr. (Function returns SQL_SUCCESS_WITH_INFO.)"
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#diagnostics

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS LONG_COLUMN_NAME");

  // When SQLDescribeCol is called with a buffer too small for the column name
  SQLCHAR col_name[5] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);

  // Then SQLDescribeCol should return SQL_SUCCESS_WITH_INFO with SQLSTATE 01004
  REQUIRE(ret == SQL_SUCCESS_WITH_INFO);
  CHECK(get_sqlstate(stmt) == "01004");

  // And the truncated name should be returned
  CHECK(std::string((char*)col_name) == "LONG");

  // And NameLengthPtr should still contain the full untruncated length
  CHECK(name_length == 16);
}

// =============================================================================
// SQL Data Types
// =============================================================================

TEST_CASE("SQLDescribeCol returns SQL_VARCHAR for VARCHAR column.", "[query]") {
  // Doc: "DataTypePtr [Output] Pointer to a buffer in which to return the SQL data
  //       type of the column. This value is read from the SQL_DESC_CONCISE_TYPE
  //       field of the IRD."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_VARCHAR_TABLE));

  // When SQLDescribeCol is called for the VARCHAR column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the data type should be SQL_VARCHAR
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_VARCHAR);
  CHECK(col_size == 100);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns SQL_DECIMAL for NUMBER column.", "[query]") {
  // Doc: "DataTypePtr [Output] Pointer to a buffer in which to return the SQL data
  //       type of the column. This value is read from the SQL_DESC_CONCISE_TYPE
  //       field of the IRD."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_NUMBER_TABLE));

  // When SQLDescribeCol is called for the NUMBER column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the data type should be SQL_DECIMAL
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_DECIMAL);
  CHECK(col_size == 10);
  CHECK(decimal_digits == 2);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns SQL_BIT for BOOLEAN column.", "[query]") {
  // Doc: "DataTypePtr [Output] Pointer to a buffer in which to return the SQL data
  //       type of the column. This value is read from the SQL_DESC_CONCISE_TYPE
  //       field of the IRD."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_BOOL_TABLE));

  // When SQLDescribeCol is called for the BOOLEAN column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the data type should be SQL_BIT
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_BIT);
  CHECK(col_size == 1);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns SQL_DOUBLE for FLOAT column.", "[query]") {
  // Doc: "DataTypePtr [Output] Pointer to a buffer in which to return the SQL data
  //       type of the column. This value is read from the SQL_DESC_CONCISE_TYPE
  //       field of the IRD."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_FLOAT_TABLE));

  // When SQLDescribeCol is called for the FLOAT column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the data type should be SQL_DOUBLE
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_DOUBLE);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns SQL_TYPE_DATE for DATE column.", "[query]") {
  // Doc: "In ODBC 3.x, SQL_TYPE_DATE, SQL_TYPE_TIME, or SQL_TYPE_TIMESTAMP is
  //       returned in *DataTypePtr for date, time, or timestamp data, respectively."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_DATE_TABLE));

  // When SQLDescribeCol is called for the DATE column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the data type should be SQL_TYPE_DATE
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_TYPE_DATE);
  CHECK(col_size == 10);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns SQL_TYPE_TIMESTAMP for TIMESTAMP_NTZ column.", "[query]") {
  // Doc: "In ODBC 3.x, SQL_TYPE_DATE, SQL_TYPE_TIME, or SQL_TYPE_TIMESTAMP is
  //       returned in *DataTypePtr for date, time, or timestamp data, respectively."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_TIMESTAMP_TABLE));

  // When SQLDescribeCol is called for the TIMESTAMP_NTZ column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then the data type should be SQL_TYPE_TIMESTAMP
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_TYPE_TIMESTAMP);
  CHECK(col_size == 29);
  CHECK(decimal_digits == 9);
  CHECK(nullable == SQL_NULLABLE);
}

// =============================================================================
// Column Size
// =============================================================================

TEST_CASE("SQLDescribeCol returns correct column size for VARCHAR.", "[query]") {
  // Doc: "ColumnSizePtr [Output] Pointer to a buffer in which to return the size
  //       (in characters) of the column on the data source."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_SIZE_VARCHAR_TABLE));

  // When SQLDescribeCol is called for the VARCHAR(200) column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then column size should be 200
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_VARCHAR);
  CHECK(col_size == 200);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns precision as column size for NUMBER.", "[query]") {
  // Doc: "ColumnSizePtr [Output] Pointer to a buffer in which to return the size
  //       (in characters) of the column on the data source."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_SIZE_NUMBER_TABLE));

  // When SQLDescribeCol is called for the NUMBER(12,3) column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then column size should be 12 (precision)
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_DECIMAL);
  CHECK(col_size == 12);
  CHECK(decimal_digits == 3);
  CHECK(nullable == SQL_NULLABLE);
}

// =============================================================================
// Decimal Digits
// =============================================================================

TEST_CASE("SQLDescribeCol returns scale as decimal digits for NUMBER.", "[query]") {
  // Doc: "DecimalDigitsPtr [Output] Pointer to a buffer in which to return the
  //       number of decimal digits of the column on the data source. If the number
  //       of decimal digits cannot be determined or is not applicable, the driver
  //       returns 0."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_DIGITS_TABLE));

  // When SQLDescribeCol is called for the NUMBER(10,4) column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then decimal digits should be 4 (scale)
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_DECIMAL);
  CHECK(col_size == 10);
  CHECK(decimal_digits == 4);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns 0 decimal digits for non-numeric types.", "[query]") {
  // Doc: "DecimalDigitsPtr [Output] ... If the number of decimal digits cannot be
  //       determined or is not applicable, the driver returns 0."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_DIGITS_VARCHAR_TABLE));

  // When SQLDescribeCol is called for the VARCHAR column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = -1;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then decimal digits should be 0
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_VARCHAR);
  CHECK(col_size == 50);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}

// =============================================================================
// Nullability
// =============================================================================

TEST_CASE("SQLDescribeCol returns SQL_NULLABLE for nullable column.", "[query]") {
  // Doc: "NullablePtr [Output] Pointer to a buffer in which to return a value
  //       that indicates whether the column allows NULL values."
  // Doc: "SQL_NULLABLE: The column allows NULL values."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_NULLABLE_TABLE));

  // When SQLDescribeCol is called for a nullable column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = -1;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then nullable should be SQL_NULLABLE
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_VARCHAR);
  CHECK(col_size == 50);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}

TEST_CASE("SQLDescribeCol returns SQL_NO_NULLS for NOT NULL column.", "[query]") {
  // Doc: "SQL_NO_NULLS: The column does not allow NULL values."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT val FROM " + std::string(readonly_db::DESC_NOTNULL_TABLE));

  // When SQLDescribeCol is called for a NOT NULL column
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = -1;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then nullable should be SQL_NO_NULLS
  CHECK(std::string((char*)col_name) == "VAL");
  CHECK(name_length == 3);
  CHECK(data_type == SQL_VARCHAR);
  CHECK(col_size == 50);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NO_NULLS);
}

// =============================================================================
// Column Number Errors
// =============================================================================

TEST_CASE("SQLDescribeCol returns 07009 for column number 0 without bookmarks.", "[query]") {
  // Doc: "07009 - Invalid descriptor index: (DM) The value specified for the
  //       argument ColumnNumber was equal to 0, and the SQL_ATTR_USE_BOOKMARKS
  //       statement option was SQL_UB_OFF."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#diagnostics

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS value");

  // When SQLDescribeCol is called with ColumnNumber = 0
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 0, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);

  // Then SQLDescribeCol should return SQL_ERROR with SQLSTATE 07009
  REQUIRE(ret == SQL_ERROR);
  CHECK(get_sqlstate(stmt) == "07009");
}

TEST_CASE("SQLDescribeCol returns 07009 for out-of-range column number.", "[query]") {
  // Doc: "07009 - Invalid descriptor index: ... The value specified for the
  //       argument ColumnNumber was greater than the number of columns in the
  //       result set."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#diagnostics

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS value");

  // When SQLDescribeCol is called with ColumnNumber > number of columns
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 100, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);

  // Then SQLDescribeCol should return SQL_ERROR with SQLSTATE 07009
  REQUIRE(ret == SQL_ERROR);
  CHECK(get_sqlstate(stmt) == "07009");
}

// =============================================================================
// Buffer Errors
// =============================================================================

TEST_CASE("SQLDescribeCol returns HY090 when BufferLength is less than 0.", "[query]") {
  // Doc: "HY090 - Invalid string or buffer length: (DM) The value specified for
  //       argument BufferLength was less than 0."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#diagnostics

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS value");

  // When SQLDescribeCol is called with BufferLength < 0
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, -1, &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);

  // Then SQLDescribeCol should return SQL_ERROR with SQLSTATE HY090
  REQUIRE(ret == SQL_ERROR);
  CHECK(get_sqlstate(stmt) == "HY090");
}

// =============================================================================
// State Errors
// =============================================================================

TEST_CASE("SQLDescribeCol returns HY010 when called before prepare or execute.", "[query]") {
  // Doc: "HY010 - Function sequence error: (DM) The function was called prior
  //       to calling SQLPrepare, SQLExecute, or a catalog function on the
  //       statement handle."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#diagnostics

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.createStatement();

  // When SQLDescribeCol is called without any prepare or execute
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);

  // Then SQLDescribeCol should return SQL_ERROR with SQLSTATE HY010
  REQUIRE(ret == SQL_ERROR);
  CHECK(get_sqlstate(stmt) == "HY010");
}

// =============================================================================
// NULL Output Pointers
// =============================================================================

TEST_CASE("SQLDescribeCol with NULL ColumnName still returns NameLengthPtr.", "[query]") {
  // Doc: "If ColumnName is NULL, NameLengthPtr will still return the total number
  //       of characters (excluding the null-termination character for character
  //       data) available to return in the buffer pointed to by ColumnName."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#arguments

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS MY_COL");

  // When SQLDescribeCol is called with NULL ColumnName
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  SQLRETURN ret =
      SQLDescribeCol(stmt.getHandle(), 1, NULL, 0, &name_length, &data_type, &col_size, &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then NameLengthPtr should contain the full column name length
  CHECK(name_length == 6);

  // And other output values should still be populated
  CHECK(data_type != 0);
}

TEST_CASE("SQLDescribeCol succeeds when all output pointers are NULL.", "[query]") {
  // Doc: "SQLDescribeCol returns the result descriptor - column name, type,
  //       column size, decimal digits, and nullability - for one column in the
  //       result set."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#summary

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.execute("SELECT 42 AS value");

  // When SQLDescribeCol is called with all output pointers NULL
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, NULL, 0, NULL, NULL, NULL, NULL, NULL);

  // Then SQLDescribeCol should succeed
  CHECK(ret == SQL_SUCCESS);
}

// =============================================================================
// After SQLPrepare (before SQLExecute)
// =============================================================================

TEST_CASE("SQLDescribeCol returns metadata after SQLPrepare.", "[query]") {
  // Doc: "An application typically calls SQLDescribeCol after a call to SQLPrepare
  //       and before or after the associated call to SQLExecute."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#comments

  // Given Snowflake client is logged in
  Connection conn;
  auto stmt = conn.createStatement();

  // When a SELECT statement is prepared but not executed
  SQLRETURN ret = SQLPrepare(stmt.getHandle(), (SQLCHAR*)"SELECT 42 AS PREP_COL", SQL_NTS);
  CHECK_ODBC(ret, stmt);

  // Then SQLDescribeCol should return metadata for the prepared statement
  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;
  ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                       &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // And the column name should match
  CHECK(std::string((char*)col_name) == "PREP_COL");
  CHECK(name_length == 8);
}

// =============================================================================
// Multiple Columns
// =============================================================================

TEST_CASE("SQLDescribeCol returns correct metadata for each column in a multi-column result.", "[query]") {
  // Doc: "SQLDescribeCol returns the result descriptor - column name, type,
  //       column size, decimal digits, and nullability - for one column in the
  //       result set."
  // https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqldescribecol-function#summary

  // Given Snowflake client is logged in
  Connection conn(get_readonly_db_connection_string());
  auto stmt = conn.execute("SELECT strcol, numcol, boolcol FROM " + std::string(readonly_db::DESC_MULTI_TABLE));

  SQLCHAR col_name[128] = {0};
  SQLSMALLINT name_length = 0;
  SQLSMALLINT data_type = 0;
  SQLULEN col_size = 0;
  SQLSMALLINT decimal_digits = 0;
  SQLSMALLINT nullable = 0;

  // When SQLDescribeCol is called for column 1 (VARCHAR)
  SQLRETURN ret = SQLDescribeCol(stmt.getHandle(), 1, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                                 &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then column 1 should be VARCHAR with size 50
  CHECK(std::string((char*)col_name) == "STRCOL");
  CHECK(name_length == 6);
  CHECK(data_type == SQL_VARCHAR);
  CHECK(col_size == 50);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);

  // When SQLDescribeCol is called for column 2 (NUMBER)
  ret = SQLDescribeCol(stmt.getHandle(), 2, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                       &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then column 2 should be DECIMAL with precision 8 and scale 2
  CHECK(std::string((char*)col_name) == "NUMCOL");
  CHECK(name_length == 6);
  CHECK(data_type == SQL_DECIMAL);
  CHECK(col_size == 8);
  CHECK(decimal_digits == 2);
  CHECK(nullable == SQL_NULLABLE);

  // When SQLDescribeCol is called for column 3 (BOOLEAN)
  ret = SQLDescribeCol(stmt.getHandle(), 3, col_name, sizeof(col_name), &name_length, &data_type, &col_size,
                       &decimal_digits, &nullable);
  CHECK_ODBC(ret, stmt);

  // Then column 3 should be BIT
  CHECK(std::string((char*)col_name) == "BOOLCOL");
  CHECK(name_length == 7);
  CHECK(data_type == SQL_BIT);
  CHECK(col_size == 1);
  CHECK(decimal_digits == 0);
  CHECK(nullable == SQL_NULLABLE);
}
