line-length = 120
extend-exclude = [
    '.hatch/',
    'src/snowflake/connector/_core',
    'src/snowflake/connector/_internal/protobuf_gen',
    'src/snowflake/connector/_internal/arrow_context.py'
]

[lint]
select = [
    'B',                        # flake8-bugbear
    'D',                        # pydocstyle
    'E',                        # pycodestyle
    'F',                        # pyflakes
    'I',                        # isort
    'RUF100',                   # check for valid noqa directives
    'UP',                       # pyupgrade
    'W',                        # pycodestyle
]
ignore = [
    'D100',                     # Missing docstring in public class
    'D101',                     # Missing docstring in public class
    'D102',                     # Missing docstring in public method
    'D104',                     # Missing docstring in public package
    'D105',                     # Missing docstring in magic method
    'D107',                     # Missing docstring in `__init__`
    'D400',                     # First line should end with a period
    'D205',                     # 1 blank line required between summary line and description
]

[lint.per-file-ignores]
'tests/**' = ['D']

[lint.pydocstyle]
convention = 'pep257'

[lint.isort]
known-first-party = ['snowflake']
lines-after-imports = 2
lines-between-types = 1
order-by-type = true

[format]
quote-style = "double"
indent-style = "space"
docstring-code-line-length = 100
docstring-code-format = true