"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _StatusCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StatusCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StatusCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STATUS_CODE_UNSPECIFIED: _StatusCode.ValueType  # 0
    STATUS_CODE_OK: _StatusCode.ValueType  # 1
    STATUS_CODE_AUTHENTICATION_ERROR: _StatusCode.ValueType  # 2
    STATUS_CODE_NOT_IMPLEMENTED: _StatusCode.ValueType  # 3
    STATUS_CODE_NOT_FOUND: _StatusCode.ValueType  # 4
    STATUS_CODE_ALREADY_EXISTS: _StatusCode.ValueType  # 5
    STATUS_CODE_INVALID_ARGUMENT: _StatusCode.ValueType  # 6
    STATUS_CODE_INVALID_STATE: _StatusCode.ValueType  # 7
    STATUS_CODE_INVALID_DATA: _StatusCode.ValueType  # 8
    STATUS_CODE_IO: _StatusCode.ValueType  # 9
    STATUS_CODE_CANCELLED: _StatusCode.ValueType  # 10
    STATUS_CODE_UNAUTHENTICATED: _StatusCode.ValueType  # 11
    STATUS_CODE_UNAUTHORIZED: _StatusCode.ValueType  # 12
    STATUS_CODE_GENERIC_ERROR: _StatusCode.ValueType  # 13
    STATUS_CODE_INTERNAL_ERROR: _StatusCode.ValueType  # 14
    STATUS_CODE_MISSING_PARAMETER: _StatusCode.ValueType  # 15
    STATUS_CODE_INVALID_PARAMETER_VALUE: _StatusCode.ValueType  # 16
    STATUS_CODE_LOGIN_ERROR: _StatusCode.ValueType  # 17

class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper):
    """Status codes corresponding to Thrift StatusCode enum"""

STATUS_CODE_UNSPECIFIED: StatusCode.ValueType  # 0
STATUS_CODE_OK: StatusCode.ValueType  # 1
STATUS_CODE_AUTHENTICATION_ERROR: StatusCode.ValueType  # 2
STATUS_CODE_NOT_IMPLEMENTED: StatusCode.ValueType  # 3
STATUS_CODE_NOT_FOUND: StatusCode.ValueType  # 4
STATUS_CODE_ALREADY_EXISTS: StatusCode.ValueType  # 5
STATUS_CODE_INVALID_ARGUMENT: StatusCode.ValueType  # 6
STATUS_CODE_INVALID_STATE: StatusCode.ValueType  # 7
STATUS_CODE_INVALID_DATA: StatusCode.ValueType  # 8
STATUS_CODE_IO: StatusCode.ValueType  # 9
STATUS_CODE_CANCELLED: StatusCode.ValueType  # 10
STATUS_CODE_UNAUTHENTICATED: StatusCode.ValueType  # 11
STATUS_CODE_UNAUTHORIZED: StatusCode.ValueType  # 12
STATUS_CODE_GENERIC_ERROR: StatusCode.ValueType  # 13
STATUS_CODE_INTERNAL_ERROR: StatusCode.ValueType  # 14
STATUS_CODE_MISSING_PARAMETER: StatusCode.ValueType  # 15
STATUS_CODE_INVALID_PARAMETER_VALUE: StatusCode.ValueType  # 16
STATUS_CODE_LOGIN_ERROR: StatusCode.ValueType  # 17
Global___StatusCode: _TypeAlias = StatusCode  # noqa: Y015

class _InfoCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _InfoCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_InfoCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    INFO_CODE_UNSPECIFIED: _InfoCode.ValueType  # 0
    INFO_CODE_VENDOR_NAME: _InfoCode.ValueType  # 1
    INFO_CODE_VENDOR_VERSION: _InfoCode.ValueType  # 2
    INFO_CODE_VENDOR_ARROW_VERSION: _InfoCode.ValueType  # 3
    INFO_CODE_VENDOR_SQL: _InfoCode.ValueType  # 101
    INFO_CODE_VENDOR_SUBSTRAIT: _InfoCode.ValueType  # 102
    INFO_CODE_VENDOR_SUBSTRAIT_MIN_VERSION: _InfoCode.ValueType  # 103
    INFO_CODE_VENDOR_SUBSTRAIT_MAX_VERSION: _InfoCode.ValueType  # 104
    INFO_CODE_DRIVER_NAME: _InfoCode.ValueType  # 201
    INFO_CODE_DRIVER_VERSION: _InfoCode.ValueType  # 202
    INFO_CODE_DRIVER_ARROW_VERSION: _InfoCode.ValueType  # 203
    INFO_CODE_DRIVER_ADBC_VERSION: _InfoCode.ValueType  # 204

class InfoCode(_InfoCode, metaclass=_InfoCodeEnumTypeWrapper):
    """Info codes corresponding to Thrift InfoCode enum"""

INFO_CODE_UNSPECIFIED: InfoCode.ValueType  # 0
INFO_CODE_VENDOR_NAME: InfoCode.ValueType  # 1
INFO_CODE_VENDOR_VERSION: InfoCode.ValueType  # 2
INFO_CODE_VENDOR_ARROW_VERSION: InfoCode.ValueType  # 3
INFO_CODE_VENDOR_SQL: InfoCode.ValueType  # 101
INFO_CODE_VENDOR_SUBSTRAIT: InfoCode.ValueType  # 102
INFO_CODE_VENDOR_SUBSTRAIT_MIN_VERSION: InfoCode.ValueType  # 103
INFO_CODE_VENDOR_SUBSTRAIT_MAX_VERSION: InfoCode.ValueType  # 104
INFO_CODE_DRIVER_NAME: InfoCode.ValueType  # 201
INFO_CODE_DRIVER_VERSION: InfoCode.ValueType  # 202
INFO_CODE_DRIVER_ARROW_VERSION: InfoCode.ValueType  # 203
INFO_CODE_DRIVER_ADBC_VERSION: InfoCode.ValueType  # 204
Global___InfoCode: _TypeAlias = InfoCode  # noqa: Y015

@_typing.final
class ErrorDetail(_message.Message):
    """Error detail message"""

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ErrorDetail: _TypeAlias = ErrorDetail  # noqa: Y015

@_typing.final
class AuthenticationError(_message.Message):
    """Authentication error details"""

    DESCRIPTOR: _descriptor.Descriptor

    DETAIL_FIELD_NUMBER: _builtins.int
    detail: _builtins.str
    def __init__(
        self,
        *,
        detail: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["detail", b"detail"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AuthenticationError: _TypeAlias = AuthenticationError  # noqa: Y015

@_typing.final
class GenericError(_message.Message):
    """Generic error (empty message)"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GenericError: _TypeAlias = GenericError  # noqa: Y015

@_typing.final
class InternalError(_message.Message):
    """Internal error (empty message)"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___InternalError: _TypeAlias = InternalError  # noqa: Y015

@_typing.final
class LoginError(_message.Message):
    """Login error details"""

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    code: _builtins.int
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        code: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoginError: _TypeAlias = LoginError  # noqa: Y015

@_typing.final
class MissingParameter(_message.Message):
    """Missing parameter error"""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMETER_FIELD_NUMBER: _builtins.int
    parameter: _builtins.str
    def __init__(
        self,
        *,
        parameter: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["parameter", b"parameter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___MissingParameter: _TypeAlias = MissingParameter  # noqa: Y015

@_typing.final
class InvalidParameterValue(_message.Message):
    """Invalid parameter value error"""

    DESCRIPTOR: _descriptor.Descriptor

    PARAMETER_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    EXPLANATION_FIELD_NUMBER: _builtins.int
    parameter: _builtins.str
    value: _builtins.str
    explanation: _builtins.str
    def __init__(
        self,
        *,
        parameter: _builtins.str = ...,
        value: _builtins.str = ...,
        explanation: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_explanation", b"_explanation", "explanation", b"explanation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_explanation", b"_explanation", "explanation", b"explanation", "parameter", b"parameter", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__explanation: _TypeAlias = _typing.Literal["explanation"]  # noqa: Y015
    _WhichOneofArgType__explanation: _TypeAlias = _typing.Literal["_explanation", b"_explanation"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__explanation) -> _WhichOneofReturnType__explanation | None: ...

Global___InvalidParameterValue: _TypeAlias = InvalidParameterValue  # noqa: Y015

@_typing.final
class DriverError(_message.Message):
    """Driver error union (using oneof)"""

    DESCRIPTOR: _descriptor.Descriptor

    AUTH_ERROR_FIELD_NUMBER: _builtins.int
    GENERIC_ERROR_FIELD_NUMBER: _builtins.int
    INTERNAL_ERROR_FIELD_NUMBER: _builtins.int
    MISSING_PARAMETER_FIELD_NUMBER: _builtins.int
    INVALID_PARAMETER_VALUE_FIELD_NUMBER: _builtins.int
    LOGIN_ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def auth_error(self) -> Global___AuthenticationError: ...
    @_builtins.property
    def generic_error(self) -> Global___GenericError: ...
    @_builtins.property
    def internal_error(self) -> Global___InternalError: ...
    @_builtins.property
    def missing_parameter(self) -> Global___MissingParameter: ...
    @_builtins.property
    def invalid_parameter_value(self) -> Global___InvalidParameterValue: ...
    @_builtins.property
    def login_error(self) -> Global___LoginError: ...
    def __init__(
        self,
        *,
        auth_error: Global___AuthenticationError | None = ...,
        generic_error: Global___GenericError | None = ...,
        internal_error: Global___InternalError | None = ...,
        missing_parameter: Global___MissingParameter | None = ...,
        invalid_parameter_value: Global___InvalidParameterValue | None = ...,
        login_error: Global___LoginError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["auth_error", b"auth_error", "error_type", b"error_type", "generic_error", b"generic_error", "internal_error", b"internal_error", "invalid_parameter_value", b"invalid_parameter_value", "login_error", b"login_error", "missing_parameter", b"missing_parameter"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_error", b"auth_error", "error_type", b"error_type", "generic_error", b"generic_error", "internal_error", b"internal_error", "invalid_parameter_value", b"invalid_parameter_value", "login_error", b"login_error", "missing_parameter", b"missing_parameter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_error_type: _TypeAlias = _typing.Literal["auth_error", "generic_error", "internal_error", "missing_parameter", "invalid_parameter_value", "login_error"]  # noqa: Y015
    _WhichOneofArgType_error_type: _TypeAlias = _typing.Literal["error_type", b"error_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_error_type) -> _WhichOneofReturnType_error_type | None: ...

Global___DriverError: _TypeAlias = DriverError  # noqa: Y015

@_typing.final
class DriverException(_message.Message):
    """Driver exception"""

    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    STATUS_CODE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    REPORT_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    status_code: Global___StatusCode.ValueType
    report: _builtins.str
    @_builtins.property
    def error(self) -> Global___DriverError: ...
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
        status_code: Global___StatusCode.ValueType = ...,
        error: Global___DriverError | None = ...,
        report: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "message", b"message", "report", b"report", "status_code", b"status_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DriverException: _TypeAlias = DriverException  # noqa: Y015

@_typing.final
class ColumnMetadata(_message.Message):
    """Column metadata for description"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    PRECISION_FIELD_NUMBER: _builtins.int
    SCALE_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    BYTE_LENGTH_FIELD_NUMBER: _builtins.int
    NULLABLE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    type: _builtins.str
    precision: _builtins.int
    scale: _builtins.int
    length: _builtins.int
    byte_length: _builtins.int
    nullable: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        type: _builtins.str = ...,
        precision: _builtins.int | None = ...,
        scale: _builtins.int | None = ...,
        length: _builtins.int | None = ...,
        byte_length: _builtins.int | None = ...,
        nullable: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_byte_length", b"_byte_length", "_length", b"_length", "_precision", b"_precision", "_scale", b"_scale", "byte_length", b"byte_length", "length", b"length", "precision", b"precision", "scale", b"scale"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_byte_length", b"_byte_length", "_length", b"_length", "_precision", b"_precision", "_scale", b"_scale", "byte_length", b"byte_length", "length", b"length", "name", b"name", "nullable", b"nullable", "precision", b"precision", "scale", b"scale", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__byte_length: _TypeAlias = _typing.Literal["byte_length"]  # noqa: Y015
    _WhichOneofArgType__byte_length: _TypeAlias = _typing.Literal["_byte_length", b"_byte_length"]  # noqa: Y015
    _WhichOneofReturnType__length: _TypeAlias = _typing.Literal["length"]  # noqa: Y015
    _WhichOneofArgType__length: _TypeAlias = _typing.Literal["_length", b"_length"]  # noqa: Y015
    _WhichOneofReturnType__precision: _TypeAlias = _typing.Literal["precision"]  # noqa: Y015
    _WhichOneofArgType__precision: _TypeAlias = _typing.Literal["_precision", b"_precision"]  # noqa: Y015
    _WhichOneofReturnType__scale: _TypeAlias = _typing.Literal["scale"]  # noqa: Y015
    _WhichOneofArgType__scale: _TypeAlias = _typing.Literal["_scale", b"_scale"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__byte_length) -> _WhichOneofReturnType__byte_length | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__length) -> _WhichOneofReturnType__length | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__precision) -> _WhichOneofReturnType__precision | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__scale) -> _WhichOneofReturnType__scale | None: ...

Global___ColumnMetadata: _TypeAlias = ColumnMetadata  # noqa: Y015

@_typing.final
class ExecuteResult(_message.Message):
    """Execute result"""

    DESCRIPTOR: _descriptor.Descriptor

    STREAM_FIELD_NUMBER: _builtins.int
    ROWS_AFFECTED_FIELD_NUMBER: _builtins.int
    QUERY_ID_FIELD_NUMBER: _builtins.int
    COLUMNS_FIELD_NUMBER: _builtins.int
    STATEMENT_TYPE_ID_FIELD_NUMBER: _builtins.int
    rows_affected: _builtins.int
    query_id: _builtins.str
    statement_type_id: _builtins.int
    @_builtins.property
    def stream(self) -> Global___ArrowArrayStreamPtr: ...
    @_builtins.property
    def columns(self) -> _containers.RepeatedCompositeFieldContainer[Global___ColumnMetadata]: ...
    def __init__(
        self,
        *,
        stream: Global___ArrowArrayStreamPtr | None = ...,
        rows_affected: _builtins.int | None = ...,
        query_id: _builtins.str = ...,
        columns: _abc.Iterable[Global___ColumnMetadata] | None = ...,
        statement_type_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_rows_affected", b"_rows_affected", "_statement_type_id", b"_statement_type_id", "rows_affected", b"rows_affected", "statement_type_id", b"statement_type_id", "stream", b"stream"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_rows_affected", b"_rows_affected", "_statement_type_id", b"_statement_type_id", "columns", b"columns", "query_id", b"query_id", "rows_affected", b"rows_affected", "statement_type_id", b"statement_type_id", "stream", b"stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__rows_affected: _TypeAlias = _typing.Literal["rows_affected"]  # noqa: Y015
    _WhichOneofArgType__rows_affected: _TypeAlias = _typing.Literal["_rows_affected", b"_rows_affected"]  # noqa: Y015
    _WhichOneofReturnType__statement_type_id: _TypeAlias = _typing.Literal["statement_type_id"]  # noqa: Y015
    _WhichOneofArgType__statement_type_id: _TypeAlias = _typing.Literal["_statement_type_id", b"_statement_type_id"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__rows_affected) -> _WhichOneofReturnType__rows_affected | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__statement_type_id) -> _WhichOneofReturnType__statement_type_id | None: ...

Global___ExecuteResult: _TypeAlias = ExecuteResult  # noqa: Y015

@_typing.final
class PartitionedResult(_message.Message):
    """Partitioned result"""

    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    PARTITIONS_FIELD_NUMBER: _builtins.int
    ROWS_AFFECTED_FIELD_NUMBER: _builtins.int
    schema: _builtins.int
    rows_affected: _builtins.int
    @_builtins.property
    def partitions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        schema: _builtins.int = ...,
        partitions: _abc.Iterable[_builtins.bytes] | None = ...,
        rows_affected: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_rows_affected", b"_rows_affected", "rows_affected", b"rows_affected"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_rows_affected", b"_rows_affected", "partitions", b"partitions", "rows_affected", b"rows_affected", "schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__rows_affected: _TypeAlias = _typing.Literal["rows_affected"]  # noqa: Y015
    _WhichOneofArgType__rows_affected: _TypeAlias = _typing.Literal["_rows_affected", b"_rows_affected"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__rows_affected) -> _WhichOneofReturnType__rows_affected | None: ...

Global___PartitionedResult: _TypeAlias = PartitionedResult  # noqa: Y015

@_typing.final
class DatabaseHandle(_message.Message):
    """Database handle"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    MAGIC_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    magic: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        magic: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "magic", b"magic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseHandle: _TypeAlias = DatabaseHandle  # noqa: Y015

@_typing.final
class ConnectionHandle(_message.Message):
    """Connection handle"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    MAGIC_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    magic: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        magic: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "magic", b"magic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionHandle: _TypeAlias = ConnectionHandle  # noqa: Y015

@_typing.final
class StatementHandle(_message.Message):
    """Statement handle"""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    MAGIC_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    magic: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        magic: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "magic", b"magic"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementHandle: _TypeAlias = StatementHandle  # noqa: Y015

@_typing.final
class ArrowArrayStreamPtr(_message.Message):
    """Arrow array stream pointer"""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ArrowArrayStreamPtr: _TypeAlias = ArrowArrayStreamPtr  # noqa: Y015

@_typing.final
class ArrowSchemaPtr(_message.Message):
    """Arrow schema pointer"""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ArrowSchemaPtr: _TypeAlias = ArrowSchemaPtr  # noqa: Y015

@_typing.final
class ArrowArrayPtr(_message.Message):
    """Arrow array pointer"""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ArrowArrayPtr: _TypeAlias = ArrowArrayPtr  # noqa: Y015

@_typing.final
class BinaryDataPtr(_message.Message):
    """=============================================================================
    POINTER TYPES - For passing data references to core
    =============================================================================

    Pointer to raw binary data in memory with explicit length.
    Used for passing data from language wrappers without copying.

    Both JSON and CSV use this same pointer type since both point to raw bytes:
    - JSON: pointer to UTF-8 encoded JSON bytes (e.g., from json_str.encode('utf-8'))
    - CSV: pointer to raw CSV file bytes
    """

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    """8-byte pointer (encoded as little-endian)"""
    length: _builtins.int
    """Length of data in bytes"""
    def __init__(
        self,
        *,
        value: _builtins.bytes = ...,
        length: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["length", b"length", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BinaryDataPtr: _TypeAlias = BinaryDataPtr  # noqa: Y015

@_typing.final
class QueryBindings(_message.Message):
    """Union of all binding types.
    Both variants use BinaryDataPtr since both point to raw bytes in memory.
    """

    DESCRIPTOR: _descriptor.Descriptor

    JSON_FIELD_NUMBER: _builtins.int
    CSV_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def json(self) -> Global___BinaryDataPtr:
        """Pointer to UTF-8 encoded JSON bytes"""

    @_builtins.property
    def csv(self) -> Global___BinaryDataPtr:
        """Pointer to raw CSV bytes"""

    def __init__(
        self,
        *,
        json: Global___BinaryDataPtr | None = ...,
        csv: Global___BinaryDataPtr | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["binding_type", b"binding_type", "csv", b"csv", "json", b"json"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binding_type", b"binding_type", "csv", b"csv", "json", b"json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_binding_type: _TypeAlias = _typing.Literal["json", "csv"]  # noqa: Y015
    _WhichOneofArgType_binding_type: _TypeAlias = _typing.Literal["binding_type", b"binding_type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_binding_type) -> _WhichOneofReturnType_binding_type | None: ...

Global___QueryBindings: _TypeAlias = QueryBindings  # noqa: Y015

@_typing.final
class DatabaseNewRequest(_message.Message):
    """Database service requests and responses"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseNewRequest: _TypeAlias = DatabaseNewRequest  # noqa: Y015

@_typing.final
class DatabaseNewResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseNewResponse: _TypeAlias = DatabaseNewResponse  # noqa: Y015

@_typing.final
class DatabaseSetOptionStringRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseSetOptionStringRequest: _TypeAlias = DatabaseSetOptionStringRequest  # noqa: Y015

@_typing.final
class DatabaseSetOptionStringResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseSetOptionStringResponse: _TypeAlias = DatabaseSetOptionStringResponse  # noqa: Y015

@_typing.final
class DatabaseSetOptionBytesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseSetOptionBytesRequest: _TypeAlias = DatabaseSetOptionBytesRequest  # noqa: Y015

@_typing.final
class DatabaseSetOptionBytesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseSetOptionBytesResponse: _TypeAlias = DatabaseSetOptionBytesResponse  # noqa: Y015

@_typing.final
class DatabaseSetOptionIntRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.int
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseSetOptionIntRequest: _TypeAlias = DatabaseSetOptionIntRequest  # noqa: Y015

@_typing.final
class DatabaseSetOptionIntResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseSetOptionIntResponse: _TypeAlias = DatabaseSetOptionIntResponse  # noqa: Y015

@_typing.final
class DatabaseSetOptionDoubleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.float
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseSetOptionDoubleRequest: _TypeAlias = DatabaseSetOptionDoubleRequest  # noqa: Y015

@_typing.final
class DatabaseSetOptionDoubleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseSetOptionDoubleResponse: _TypeAlias = DatabaseSetOptionDoubleResponse  # noqa: Y015

@_typing.final
class DatabaseInitRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseInitRequest: _TypeAlias = DatabaseInitRequest  # noqa: Y015

@_typing.final
class DatabaseInitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseInitResponse: _TypeAlias = DatabaseInitResponse  # noqa: Y015

@_typing.final
class DatabaseReleaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DB_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        db_handle: Global___DatabaseHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["db_handle", b"db_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DatabaseReleaseRequest: _TypeAlias = DatabaseReleaseRequest  # noqa: Y015

@_typing.final
class DatabaseReleaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DatabaseReleaseResponse: _TypeAlias = DatabaseReleaseResponse  # noqa: Y015

@_typing.final
class ConnectionNewRequest(_message.Message):
    """Connection service requests and responses"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionNewRequest: _TypeAlias = ConnectionNewRequest  # noqa: Y015

@_typing.final
class ConnectionNewResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionNewResponse: _TypeAlias = ConnectionNewResponse  # noqa: Y015

@_typing.final
class ConnectionSetOptionStringRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionSetOptionStringRequest: _TypeAlias = ConnectionSetOptionStringRequest  # noqa: Y015

@_typing.final
class ConnectionSetOptionStringResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionSetOptionStringResponse: _TypeAlias = ConnectionSetOptionStringResponse  # noqa: Y015

@_typing.final
class ConnectionSetOptionBytesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionSetOptionBytesRequest: _TypeAlias = ConnectionSetOptionBytesRequest  # noqa: Y015

@_typing.final
class ConnectionSetOptionBytesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionSetOptionBytesResponse: _TypeAlias = ConnectionSetOptionBytesResponse  # noqa: Y015

@_typing.final
class ConnectionSetOptionIntRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionSetOptionIntRequest: _TypeAlias = ConnectionSetOptionIntRequest  # noqa: Y015

@_typing.final
class ConnectionSetOptionIntResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionSetOptionIntResponse: _TypeAlias = ConnectionSetOptionIntResponse  # noqa: Y015

@_typing.final
class ConnectionSetOptionDoubleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.float
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionSetOptionDoubleRequest: _TypeAlias = ConnectionSetOptionDoubleRequest  # noqa: Y015

@_typing.final
class ConnectionSetOptionDoubleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionSetOptionDoubleResponse: _TypeAlias = ConnectionSetOptionDoubleResponse  # noqa: Y015

@_typing.final
class ConnectionInitRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    DB_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    @_builtins.property
    def db_handle(self) -> Global___DatabaseHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        db_handle: Global___DatabaseHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "db_handle", b"db_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "db_handle", b"db_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionInitRequest: _TypeAlias = ConnectionInitRequest  # noqa: Y015

@_typing.final
class ConnectionInitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionInitResponse: _TypeAlias = ConnectionInitResponse  # noqa: Y015

@_typing.final
class ConnectionReleaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionReleaseRequest: _TypeAlias = ConnectionReleaseRequest  # noqa: Y015

@_typing.final
class ConnectionReleaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionReleaseResponse: _TypeAlias = ConnectionReleaseResponse  # noqa: Y015

@_typing.final
class ConnectionGetInfoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    INFO_CODES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    @_builtins.property
    def info_codes(self) -> _containers.RepeatedScalarFieldContainer[Global___InfoCode.ValueType]: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        info_codes: _abc.Iterable[Global___InfoCode.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "info_codes", b"info_codes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetInfoRequest: _TypeAlias = ConnectionGetInfoRequest  # noqa: Y015

@_typing.final
class ConnectionGetInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INFO_DATA_FIELD_NUMBER: _builtins.int
    info_data: _builtins.bytes
    def __init__(
        self,
        *,
        info_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info_data", b"info_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetInfoResponse: _TypeAlias = ConnectionGetInfoResponse  # noqa: Y015

@_typing.final
class ConnectionGetObjectsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    DEPTH_FIELD_NUMBER: _builtins.int
    CATALOG_FIELD_NUMBER: _builtins.int
    DB_SCHEMA_FIELD_NUMBER: _builtins.int
    TABLE_NAME_FIELD_NUMBER: _builtins.int
    TABLE_TYPE_FIELD_NUMBER: _builtins.int
    COLUMN_NAME_FIELD_NUMBER: _builtins.int
    depth: _builtins.int
    catalog: _builtins.str
    db_schema: _builtins.str
    table_name: _builtins.str
    column_name: _builtins.str
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    @_builtins.property
    def table_type(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        depth: _builtins.int = ...,
        catalog: _builtins.str | None = ...,
        db_schema: _builtins.str | None = ...,
        table_name: _builtins.str | None = ...,
        table_type: _abc.Iterable[_builtins.str] | None = ...,
        column_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_catalog", b"_catalog", "_column_name", b"_column_name", "_db_schema", b"_db_schema", "_table_name", b"_table_name", "catalog", b"catalog", "column_name", b"column_name", "conn_handle", b"conn_handle", "db_schema", b"db_schema", "table_name", b"table_name"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_catalog", b"_catalog", "_column_name", b"_column_name", "_db_schema", b"_db_schema", "_table_name", b"_table_name", "catalog", b"catalog", "column_name", b"column_name", "conn_handle", b"conn_handle", "db_schema", b"db_schema", "depth", b"depth", "table_name", b"table_name", "table_type", b"table_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__catalog: _TypeAlias = _typing.Literal["catalog"]  # noqa: Y015
    _WhichOneofArgType__catalog: _TypeAlias = _typing.Literal["_catalog", b"_catalog"]  # noqa: Y015
    _WhichOneofReturnType__column_name: _TypeAlias = _typing.Literal["column_name"]  # noqa: Y015
    _WhichOneofArgType__column_name: _TypeAlias = _typing.Literal["_column_name", b"_column_name"]  # noqa: Y015
    _WhichOneofReturnType__db_schema: _TypeAlias = _typing.Literal["db_schema"]  # noqa: Y015
    _WhichOneofArgType__db_schema: _TypeAlias = _typing.Literal["_db_schema", b"_db_schema"]  # noqa: Y015
    _WhichOneofReturnType__table_name: _TypeAlias = _typing.Literal["table_name"]  # noqa: Y015
    _WhichOneofArgType__table_name: _TypeAlias = _typing.Literal["_table_name", b"_table_name"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__catalog) -> _WhichOneofReturnType__catalog | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__column_name) -> _WhichOneofReturnType__column_name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__db_schema) -> _WhichOneofReturnType__db_schema | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__table_name) -> _WhichOneofReturnType__table_name | None: ...

Global___ConnectionGetObjectsRequest: _TypeAlias = ConnectionGetObjectsRequest  # noqa: Y015

@_typing.final
class ConnectionGetObjectsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBJECTS_DATA_FIELD_NUMBER: _builtins.int
    objects_data: _builtins.bytes
    def __init__(
        self,
        *,
        objects_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["objects_data", b"objects_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetObjectsResponse: _TypeAlias = ConnectionGetObjectsResponse  # noqa: Y015

@_typing.final
class ConnectionGetTableSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    CATALOG_FIELD_NUMBER: _builtins.int
    DB_SCHEMA_FIELD_NUMBER: _builtins.int
    TABLE_NAME_FIELD_NUMBER: _builtins.int
    catalog: _builtins.str
    db_schema: _builtins.str
    table_name: _builtins.str
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        catalog: _builtins.str | None = ...,
        db_schema: _builtins.str | None = ...,
        table_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_catalog", b"_catalog", "_db_schema", b"_db_schema", "catalog", b"catalog", "conn_handle", b"conn_handle", "db_schema", b"db_schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_catalog", b"_catalog", "_db_schema", b"_db_schema", "catalog", b"catalog", "conn_handle", b"conn_handle", "db_schema", b"db_schema", "table_name", b"table_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__catalog: _TypeAlias = _typing.Literal["catalog"]  # noqa: Y015
    _WhichOneofArgType__catalog: _TypeAlias = _typing.Literal["_catalog", b"_catalog"]  # noqa: Y015
    _WhichOneofReturnType__db_schema: _TypeAlias = _typing.Literal["db_schema"]  # noqa: Y015
    _WhichOneofArgType__db_schema: _TypeAlias = _typing.Literal["_db_schema", b"_db_schema"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__catalog) -> _WhichOneofReturnType__catalog | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__db_schema) -> _WhichOneofReturnType__db_schema | None: ...

Global___ConnectionGetTableSchemaRequest: _TypeAlias = ConnectionGetTableSchemaRequest  # noqa: Y015

@_typing.final
class ConnectionGetTableSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_DATA_FIELD_NUMBER: _builtins.int
    schema_data: _builtins.bytes
    def __init__(
        self,
        *,
        schema_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema_data", b"schema_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetTableSchemaResponse: _TypeAlias = ConnectionGetTableSchemaResponse  # noqa: Y015

@_typing.final
class ConnectionGetTableTypesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetTableTypesRequest: _TypeAlias = ConnectionGetTableTypesRequest  # noqa: Y015

@_typing.final
class ConnectionGetTableTypesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TABLE_TYPES_DATA_FIELD_NUMBER: _builtins.int
    table_types_data: _builtins.bytes
    def __init__(
        self,
        *,
        table_types_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["table_types_data", b"table_types_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetTableTypesResponse: _TypeAlias = ConnectionGetTableTypesResponse  # noqa: Y015

@_typing.final
class ConnectionCommitRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionCommitRequest: _TypeAlias = ConnectionCommitRequest  # noqa: Y015

@_typing.final
class ConnectionCommitResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionCommitResponse: _TypeAlias = ConnectionCommitResponse  # noqa: Y015

@_typing.final
class ConnectionRollbackRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionRollbackRequest: _TypeAlias = ConnectionRollbackRequest  # noqa: Y015

@_typing.final
class ConnectionRollbackResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionRollbackResponse: _TypeAlias = ConnectionRollbackResponse  # noqa: Y015

@_typing.final
class ConnectionSetSessionParametersRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ParametersEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    PARAMETERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    @_builtins.property
    def parameters(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        parameters: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "parameters", b"parameters"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionSetSessionParametersRequest: _TypeAlias = ConnectionSetSessionParametersRequest  # noqa: Y015

@_typing.final
class ConnectionSetSessionParametersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConnectionSetSessionParametersResponse: _TypeAlias = ConnectionSetSessionParametersResponse  # noqa: Y015

@_typing.final
class ConnectionGetParameterRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
        key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle", "key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConnectionGetParameterRequest: _TypeAlias = ConnectionGetParameterRequest  # noqa: Y015

@_typing.final
class ConnectionGetParameterResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.str
    def __init__(
        self,
        *,
        value: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_value", b"_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_value", b"_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__value: _TypeAlias = _typing.Literal["value"]  # noqa: Y015
    _WhichOneofArgType__value: _TypeAlias = _typing.Literal["_value", b"_value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__value) -> _WhichOneofReturnType__value | None: ...

Global___ConnectionGetParameterResponse: _TypeAlias = ConnectionGetParameterResponse  # noqa: Y015

@_typing.final
class StatementNewRequest(_message.Message):
    """Statement service requests and responses"""

    DESCRIPTOR: _descriptor.Descriptor

    CONN_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def conn_handle(self) -> Global___ConnectionHandle: ...
    def __init__(
        self,
        *,
        conn_handle: Global___ConnectionHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["conn_handle", b"conn_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementNewRequest: _TypeAlias = StatementNewRequest  # noqa: Y015

@_typing.final
class StatementNewResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementNewResponse: _TypeAlias = StatementNewResponse  # noqa: Y015

@_typing.final
class StatementReleaseRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementReleaseRequest: _TypeAlias = StatementReleaseRequest  # noqa: Y015

@_typing.final
class StatementReleaseResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementReleaseResponse: _TypeAlias = StatementReleaseResponse  # noqa: Y015

@_typing.final
class StatementSetSqlQueryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    query: _builtins.str
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        query: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["query", b"query", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementSetSqlQueryRequest: _TypeAlias = StatementSetSqlQueryRequest  # noqa: Y015

@_typing.final
class StatementSetSqlQueryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementSetSqlQueryResponse: _TypeAlias = StatementSetSqlQueryResponse  # noqa: Y015

@_typing.final
class StatementSetSubstraitPlanRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    PLAN_FIELD_NUMBER: _builtins.int
    plan: _builtins.bytes
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        plan: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["plan", b"plan", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementSetSubstraitPlanRequest: _TypeAlias = StatementSetSubstraitPlanRequest  # noqa: Y015

@_typing.final
class StatementSetSubstraitPlanResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementSetSubstraitPlanResponse: _TypeAlias = StatementSetSubstraitPlanResponse  # noqa: Y015

@_typing.final
class StatementPrepareRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementPrepareRequest: _TypeAlias = StatementPrepareRequest  # noqa: Y015

@_typing.final
class StatementPrepareResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementPrepareResponse: _TypeAlias = StatementPrepareResponse  # noqa: Y015

@_typing.final
class StatementSetOptionStringRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "stmt_handle", b"stmt_handle", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementSetOptionStringRequest: _TypeAlias = StatementSetOptionStringRequest  # noqa: Y015

@_typing.final
class StatementSetOptionStringResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementSetOptionStringResponse: _TypeAlias = StatementSetOptionStringResponse  # noqa: Y015

@_typing.final
class StatementSetOptionBytesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "stmt_handle", b"stmt_handle", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementSetOptionBytesRequest: _TypeAlias = StatementSetOptionBytesRequest  # noqa: Y015

@_typing.final
class StatementSetOptionBytesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementSetOptionBytesResponse: _TypeAlias = StatementSetOptionBytesResponse  # noqa: Y015

@_typing.final
class StatementSetOptionIntRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "stmt_handle", b"stmt_handle", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementSetOptionIntRequest: _TypeAlias = StatementSetOptionIntRequest  # noqa: Y015

@_typing.final
class StatementSetOptionIntResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementSetOptionIntResponse: _TypeAlias = StatementSetOptionIntResponse  # noqa: Y015

@_typing.final
class StatementSetOptionDoubleRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.float
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        key: _builtins.str = ...,
        value: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "stmt_handle", b"stmt_handle", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementSetOptionDoubleRequest: _TypeAlias = StatementSetOptionDoubleRequest  # noqa: Y015

@_typing.final
class StatementSetOptionDoubleResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementSetOptionDoubleResponse: _TypeAlias = StatementSetOptionDoubleResponse  # noqa: Y015

@_typing.final
class StatementGetParameterSchemaRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementGetParameterSchemaRequest: _TypeAlias = StatementGetParameterSchemaRequest  # noqa: Y015

@_typing.final
class StatementGetParameterSchemaResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCHEMA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def schema(self) -> Global___ArrowSchemaPtr: ...
    def __init__(
        self,
        *,
        schema: Global___ArrowSchemaPtr | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["schema", b"schema"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementGetParameterSchemaResponse: _TypeAlias = StatementGetParameterSchemaResponse  # noqa: Y015

@_typing.final
class StatementBindRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    SCHEMA_FIELD_NUMBER: _builtins.int
    ARRAY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    @_builtins.property
    def schema(self) -> Global___ArrowSchemaPtr: ...
    @_builtins.property
    def array(self) -> Global___ArrowArrayPtr: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        schema: Global___ArrowSchemaPtr | None = ...,
        array: Global___ArrowArrayPtr | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "schema", b"schema", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["array", b"array", "schema", b"schema", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementBindRequest: _TypeAlias = StatementBindRequest  # noqa: Y015

@_typing.final
class StatementBindResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementBindResponse: _TypeAlias = StatementBindResponse  # noqa: Y015

@_typing.final
class StatementBindStreamRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    STREAM_FIELD_NUMBER: _builtins.int
    stream: _builtins.bytes
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        stream: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle", "stream", b"stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementBindStreamRequest: _TypeAlias = StatementBindStreamRequest  # noqa: Y015

@_typing.final
class StatementBindStreamResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StatementBindStreamResponse: _TypeAlias = StatementBindStreamResponse  # noqa: Y015

@_typing.final
class StatementExecuteQueryRequest(_message.Message):
    """Extend current StatementExecute"""

    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    BINDINGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    @_builtins.property
    def bindings(self) -> Global___QueryBindings:
        """None = no bindings"""

    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        bindings: Global___QueryBindings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_bindings", b"_bindings", "bindings", b"bindings", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_bindings", b"_bindings", "bindings", b"bindings", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__bindings: _TypeAlias = _typing.Literal["bindings"]  # noqa: Y015
    _WhichOneofArgType__bindings: _TypeAlias = _typing.Literal["_bindings", b"_bindings"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__bindings) -> _WhichOneofReturnType__bindings | None: ...

Global___StatementExecuteQueryRequest: _TypeAlias = StatementExecuteQueryRequest  # noqa: Y015

@_typing.final
class StatementExecuteQueryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def result(self) -> Global___ExecuteResult: ...
    def __init__(
        self,
        *,
        result: Global___ExecuteResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementExecuteQueryResponse: _TypeAlias = StatementExecuteQueryResponse  # noqa: Y015

@_typing.final
class StatementExecutePartitionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementExecutePartitionsRequest: _TypeAlias = StatementExecutePartitionsRequest  # noqa: Y015

@_typing.final
class StatementExecutePartitionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def result(self) -> Global___PartitionedResult: ...
    def __init__(
        self,
        *,
        result: Global___PartitionedResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementExecutePartitionsResponse: _TypeAlias = StatementExecutePartitionsResponse  # noqa: Y015

@_typing.final
class StatementReadPartitionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STMT_HANDLE_FIELD_NUMBER: _builtins.int
    PARTITION_DESCRIPTOR_FIELD_NUMBER: _builtins.int
    partition_descriptor: _builtins.bytes
    @_builtins.property
    def stmt_handle(self) -> Global___StatementHandle: ...
    def __init__(
        self,
        *,
        stmt_handle: Global___StatementHandle | None = ...,
        partition_descriptor: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["stmt_handle", b"stmt_handle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["partition_descriptor", b"partition_descriptor", "stmt_handle", b"stmt_handle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementReadPartitionRequest: _TypeAlias = StatementReadPartitionRequest  # noqa: Y015

@_typing.final
class StatementReadPartitionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PARTITION_STREAM_FIELD_NUMBER: _builtins.int
    partition_stream: _builtins.int
    def __init__(
        self,
        *,
        partition_stream: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["partition_stream", b"partition_stream"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StatementReadPartitionResponse: _TypeAlias = StatementReadPartitionResponse  # noqa: Y015

@_typing.final
class ConfigSetting(_message.Message):
    """Config setting value (union type)"""

    DESCRIPTOR: _descriptor.Descriptor

    STRING_VALUE_FIELD_NUMBER: _builtins.int
    INT_VALUE_FIELD_NUMBER: _builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: _builtins.int
    BYTES_VALUE_FIELD_NUMBER: _builtins.int
    string_value: _builtins.str
    int_value: _builtins.int
    double_value: _builtins.float
    bytes_value: _builtins.bytes
    def __init__(
        self,
        *,
        string_value: _builtins.str = ...,
        int_value: _builtins.int = ...,
        double_value: _builtins.float = ...,
        bytes_value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bytes_value", b"bytes_value", "double_value", b"double_value", "int_value", b"int_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_value", b"bytes_value", "double_value", b"double_value", "int_value", b"int_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["string_value", "int_value", "double_value", "bytes_value"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___ConfigSetting: _TypeAlias = ConfigSetting  # noqa: Y015

@_typing.final
class ConfigSection(_message.Message):
    """A config section containing key-value settings"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SettingsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___ConfigSetting: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___ConfigSetting | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SETTINGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def settings(self) -> _containers.MessageMap[_builtins.str, Global___ConfigSetting]: ...
    def __init__(
        self,
        *,
        settings: _abc.Mapping[_builtins.str, Global___ConfigSetting] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["settings", b"settings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConfigSection: _TypeAlias = ConfigSection  # noqa: Y015

@_typing.final
class ConfigLoadAllSectionsRequest(_message.Message):
    """Config service requests and responses"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ConfigLoadAllSectionsRequest: _TypeAlias = ConfigLoadAllSectionsRequest  # noqa: Y015

@_typing.final
class ConfigLoadAllSectionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SectionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___ConfigSection: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___ConfigSection | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SECTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def sections(self) -> _containers.MessageMap[_builtins.str, Global___ConfigSection]: ...
    def __init__(
        self,
        *,
        sections: _abc.Mapping[_builtins.str, Global___ConfigSection] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["sections", b"sections"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ConfigLoadAllSectionsResponse: _TypeAlias = ConfigLoadAllSectionsResponse  # noqa: Y015

SERVICE_ERROR_FIELD_NUMBER: _builtins.int
METHOD_ERROR_FIELD_NUMBER: _builtins.int
service_error: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.ServiceOptions, _builtins.str]
method_error: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MethodOptions, _builtins.str]
